test to run the tests in parallel.
I tried this because parallel execution should be much faster with all those browsers starting up and shutting down. And indeed it is: on my computer test time went from 2:16 to 1:07. However, the tests can't handle parallel execution:

Failed tests:   testInvariantFailurePlugin(com.crawljax.core.state.StateMachineTest): InvariantViolationPlugin are exeucted
  testClickUnderXPath(com.crawljax.core.configuration.UnderXPathTest): There should be 2 outgoing links expected:<2> but was:<0>
  testCorrectStateOnViolatedInvariants(com.crawljax.core.largetests.LargeFirefoxTest): OnViolatedInvariantPlugin session object has the correct currentState
  testInvariants(com.crawljax.core.largetests.LargeFirefoxTest): 0 Invariants violated
  testPluginsExecution(com.crawljax.core.plugin.PluginsTest): expected:<9> but was:<5>

Tests in error:
  com.crawljax.core.plugin.OnFireEventFailedPluginTest
  testDontClickUnderXPath(com.crawljax.core.configuration.UnderXPathTest)
  testRandomFormInput(com.crawljax.core.largetests.LargeFirefoxTest)
  testForIllegalStates(com.crawljax.core.largetests.LargeFirefoxTest)
  testDepth(com.crawljax.core.largetests.LargeFirefoxTest)
  testManualFormInput(com.crawljax.core.largetests.LargeFirefoxTest)
  testOracleComparators(com.crawljax.core.largetests.LargeFirefoxTest)
  testWaitCondition(com.crawljax.core.largetests.LargeFirefoxTest)
  testCrawledElements(com.crawljax.core.largetests.LargeFirefoxTest)
  testMultipleFormInput(com.crawljax.core.largetests.LargeFirefoxTest)